name: Build

on:
  push:
    branches:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PDF
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nictru/bsc-thesis-devcontainer
          cacheFrom: ghcr.io/nictru/bsc-thesis-devcontainer
          push: always
          runCmd: ./build.sh
