name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PDF
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nictru/bsc-thesis-devcontainer
          cacheFrom: ghcr.io/nictru/bsc-thesis-devcontainer
          push: always
          runCmd: ./build.sh

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: build/Thesis.pdf
          if-no-files-found: error

      - name: Release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build/Thesis.pdf
